language: ruby

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-1.7.25
  - jruby-9.1.2.0

matrix:
  exclude:
    - rvm: jruby-1.7.25
      gemfile: gemfiles/rails5_0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5_0.gemfile

sudo: false
